### ISSUE TITLE
Add a version using new `io` module

### ISSUE THREAD

**Issue by TyOverby** [BurntSushi/byteorder#2]
As I understand, the purpose of this crate is to prepare for a world where we no longer have the endian-writing/reading functions on Reader and Writer.  As someone that that uses those functions a lot, I would like to prepare my crates (namely [bincode](https://github.com/TyOverby/bincode)) for the new `io` crate.  I'd be willing to help do the port if you are interested.

**Comment by BurntSushi** [comment]
You should be able to use `byteorder` today with minimal changes. e.g., replace

    self.reader.read_be_i64().map_err(wrap_io)

with

    self.reader.read_i64::<BigEndian>().map_err(wrap_io)

You'll need to import `ReaderBytesExt` and `BigEndian` from `byteorder`.

Also, I'm on IRC (nick: `burntsushi`). Ping me. :-)

**Comment by TyOverby** [comment]
But `byteorder` still expects the reader to be `old_io::Reader` right?

**Comment by BurntSushi** [comment]
Oh! I see what you meant now. Yes. Currently using `old_io::Reader`. I think the transition to the new `io::Read` will be very easy because I explicitly did not use any of the extension methods that are going to get removed (I think).

If you want to start the port, that's fine with me. I probably don't want to merge to master until everything is fully baked in `std` though. Not sure when that's happening? I guess before the beta?

**Comment by TyOverby** [comment]
Sounds good.  How about a separate branch that tracks _new_ `io`?  I'll get started on the transition today or tomorrow.

**Comment by BurntSushi** [comment]
Perfect. :-)

**Comment by BurntSushi** [comment]
It looks like @tanadeau already did this! https://github.com/tanadeau/byteorder/commit/221dcc89bc7d6b2c216f97623b0f754887668224

**Comment by tanadeau** [comment]
@BurntSushi Could you create a branch so I can create a PR to it? That's assuming you still want it to be separate for now.

**Comment by BurntSushi** [comment]
@tanadeau I've just pushed a branch called `newio`. I'm not sure exactly when I should be making the switch, is `std::io` and `std::path` ready for prime time?

**Comment by tanadeau** [comment]
I just created the PR.

I think the new modules are good for regular use, but there are still missing pieces. I'm going to start using them and this library for a project I'm creating so I'll find out soon myself.

**Comment by tanadeau** [comment]
Thanks for merging!

It might be worth updating the README.md on master to mention the newio branch.

**Comment by blackbeam** [comment]
What do you think if i merge `newio` branch and provide it as an optional crate feature?
I think it will be non-breaking change.

**Comment by tanadeau** [comment]
Sounds good to me

**Comment by blackbeam** [comment]
Great! @BurntSushi, what do you think? May be a lot of typing, so i want to make sure you will merge it.

**Comment by BurntSushi** [comment]
I really don't want to have both live at the same time in the same branch.

Can you tell `Cargo.toml` to use a specific branch in the mean time?

I'd like to just move everything over to the new `io` stuff, but I don't know when the right time to strike is.

**Comment by blackbeam** [comment]
I agree with you to be honest.. just my impatience.

I think you can, but it's not an option for maintainers of cargo packages because you can't publish a package with git dependencies.

I think when both `Read` and `Write` become stable ([_around Mar 9_](http://blog.rust-lang.org/2015/02/13/Final-1.0-timeline.html))

**Comment by danburkert** [comment]
:+1: for moving over to the new IO APIs.  As I understand it the functionality provided by this library isn't really necessary with the old APIs, but it is definitely helpful with the new APIs.  I am running into this right now porting a custom Serializer/Deserializer to the new IO APIs.  Perhaps cut one final release before moving over?

**Comment by TyOverby** [comment]
:-1: for moving to the new IO apis before they are stable.  Keep old API until we no longer need `feature(io)`.

**Comment by tanadeau** [comment]
If you want to use this library with the old IO libraries, why not just pin the version in your Cargo.toml to the last release?

I'm not sure what's gained by keeping byteorder against a deprecated API that, as @danburkert mentioned, is needs it less.

**Comment by BurntSushi** [comment]
I don't think we need to wait for official stability. There is still plenty of unstable stuff to go around, and as others have mentioned, the utility of this library is tied to the new `io` library.

I will desperately try to find time this weekend to get this released with the new io. (The work is done for this library, but I'll have to fix my downstream dependencies.)

**Comment by BurntSushi** [comment]
@sfackler I think you're using this crate too? Do you have any strong opinions?

**Comment by sfackler** [comment]
I'm going to be switching rust-postgres over pretty soon.

It also seems like it should be pretty painless to support both old io and new io at the same time.

**Comment by TyOverby** [comment]
@sfackler I think the argument is mainly "which version should be the one that is the current version on cargo".

**Comment by sfackler** [comment]
@TyOverby byteorder can just define both ReaderBytesExt and ReadBytesExt and the same for Writer. It's not like they're totally incompatible or anything.

**Comment by TyOverby** [comment]
> I really don't want to have both live at the same time in the same branch.

**Comment by BurntSushi** [comment]
So I just bit the bullet and added support for `std::io` in https://github.com/BurntSushi/byteorder/commit/d3f22dc8a9c5c52ef16cb28ebc5e8262370592ca. I'm still supporting `std::old_io` as per @sfackler's suggestion. Unless there is some other complication, I'll keep it this way until `std::old_io` disappears.

I've updated [the docs](http://burntsushi.net/rustdoc/byteorder/).
